name: Healthcheck Workflow

on:
  schedule:
    - cron: '0 * * * *' # 매 1시간마다 실행
  workflow_dispatch: # 수동 트리거

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Healthcheck for domains (HTTP on port 80 only)
        id: healthcheck
        env:
          TARGETS: ${{ secrets.HEALTHCHECK_TARGETS }} # ex) example.com,test.com,...
        run: |
          # 대상 도메인 리스트 분리
          IFS=',' read -r -a targets <<< "$TARGETS"
          
          # 결과 파일 초기화
          echo "" > healthcheck_results.txt

          for domain in "${targets[@]}"; do
            echo "Checking $domain on port 80"
            http_status=$(curl -o /dev/null -s -w "%{http_code}" $domain)
          
            if [[ "$http_status" =~ ^4|5 ]]; then
              echo "$domain - FAIL (HTTP $http_status)" >> healthcheck_results.txt
            else
              echo "$domain - SUCCESS" >> healthcheck_results.txt
            fi
          done

      - name: Send Notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          failed_checks=$(grep "FAIL" healthcheck_results.txt)

          if [ -n "$failed_checks" ]; then
            message="**⚠️ Healthcheck failed for the following domains:**\n\n"

            message+=$(echo "$failed_checks" | while IFS= read -r line; do
              domain=$(echo "$line" | cut -d' ' -f1)  # 도메인 추출
              status=$(echo "$line" | cut -d' ' -f3)  # 상태 추출
              echo "❌ **$domain** is down! (HTTP $status)"
            done)

            curl -H "Content-Type: application/json" \
                 -d "{\"embeds\": [{\"title\": \"Healthcheck Failed!\", \"description\": \"$message\", \"color\": 16711680}]}" \
                 $DISCORD_WEBHOOK
          else
            echo "No failed checks. No notification sent."